/**
 * Created by Jack Wan on 5/7/18.
 */

#ifndef ARDUINO_EASY_FILTER_LIBRARY_EASYFILTER_H
#define ARDUINO_EASY_FILTER_LIBRARY_EASYFILTER_H

#include "Filter.h"

#endif //ARDUINO_EASY_FILTER_LIBRARY_EASYFILTER_H
